/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import Conectar.conectar;
import java.sql.*;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import javax.swing.SwingConstants;
import static proyecto.InterfazInicio.PanelPrincipal;

/**
 *
 * @author Francisco
 */
public class PanelConsultarEstudiante extends javax.swing.JPanel {
    DefaultTableModel modelo;
    InterfazInicio inicio;
    PanelOpcionesConsulta p1 = null;

    /**
     * Creates new form PanelConsultar
     */
    public PanelConsultarEstudiante(InterfazInicio n) {
        
        initComponents();
        mostrarusuarios("");
        inicio = n;
        
        
        JTableRegistro.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
        JTableRegistro.getTableHeader().setOpaque(false);
        JTableRegistro.getTableHeader().setBackground(new Color(32, 136, 203));
        JTableRegistro.getTableHeader().setForeground(new Color(255,255,255));
        JTableRegistro.setRowHeight(25);
        JTableRegistro.setAlignmentX(SwingConstants.CENTER);
        JTableRegistro.getColumn("Codigo").setPreferredWidth(40);
        JTableRegistro.getColumn("Codigo Plan").setPreferredWidth(45);
        JTableRegistro.getColumn("Documento Identidad").setPreferredWidth(110);
        JTableRegistro.getColumn("Email").setPreferredWidth(110);
        
    }

     void mostrarusuarios(String valor){
   String mostrar="SELECT * FROM registro WHERE CONCAT(IdEstudiante,Codigo,CodigoPlan,DocumentoIdentidad,Nombres,Apellidos,Email,Genero,TipoUsuario,Password,Foto) LIKE '%"+valor+"%'";    
   String [] titulos= {"Codigo","Codigo Plan","Documento Identidad","Nombres","Apellidos","Email","Genero","Tipo Usuario"};
   modelo=new  DefaultTableModel(null,titulos);   
   String datos []= new String[10];
   String sql="SELECT * FROM  registro"; 
        try {
            Statement st = (Statement) cn.createStatement();
            ResultSet rs = st.executeQuery(mostrar);
            while(rs.next())
            {
                datos[0] = rs.getString("Codigo");
                datos[1] = rs.getString("CodigoPlan");
                datos[2] = rs.getString("DocumentoIdentidad");
                datos[3] = rs.getString("Nombres");
                datos[4] = rs.getString("Apellidos");
                datos[5] = rs.getString("Email");
                datos[6] = rs.getString("Genero");
                datos[7] = rs.getString("TipoUsuario");
                datos[8] = rs.getString("Password");
//                datos[9] = rs.getBytes("Foto");
               
                        
                modelo.addRow(datos);
            }
            JTableRegistro.setModel(modelo);
       } catch (Exception e) {
             JOptionPane.showMessageDialog(this,e);

        }
  
  
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        TxtBuscar = new javax.swing.JTextField();
        BtnMostrarTodos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableRegistro = new javax.swing.JTable();
        BtnAtras = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Base de Datos Estudiante"));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Busqueda: ");

        TxtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtBuscarKeyReleased(evt);
            }
        });

        BtnMostrarTodos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/button_mostrar-todo.png"))); // NOI18N
        BtnMostrarTodos.setBorderPainted(false);
        BtnMostrarTodos.setContentAreaFilled(false);
        BtnMostrarTodos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/button_mostrar-todo_on.png"))); // NOI18N
        BtnMostrarTodos.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/button_mostrar-todo_on.png"))); // NOI18N
        BtnMostrarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMostrarTodosActionPerformed(evt);
            }
        });

        JTableRegistro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        JTableRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JTableRegistro.setFocusable(false);
        JTableRegistro.setIntercellSpacing(new java.awt.Dimension(0, 0));
        JTableRegistro.setRowHeight(25);
        JTableRegistro.setSelectionBackground(new java.awt.Color(232, 57, 95));
        JTableRegistro.setShowVerticalLines(false);
        jScrollPane1.setViewportView(JTableRegistro);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnMostrarTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 578, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 970, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(TxtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(BtnMostrarTodos))
                .addGap(52, 52, 52)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 1020, 620));

        BtnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/button_atras.png"))); // NOI18N
        BtnAtras.setBorderPainted(false);
        BtnAtras.setContentAreaFilled(false);
        BtnAtras.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/button_atras_on.png"))); // NOI18N
        BtnAtras.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/button_atras_on.png"))); // NOI18N
        BtnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAtrasActionPerformed(evt);
            }
        });
        add(BtnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(838, 683, 160, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void TxtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtBuscarKeyReleased
        // TODO add your handling code here:
        
        mostrarusuarios(TxtBuscar.getText());
    }//GEN-LAST:event_TxtBuscarKeyReleased

    private void BtnMostrarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMostrarTodosActionPerformed
        // TODO add your handling code here:
        
        mostrarusuarios("");
        TxtBuscar.setText("");
    }//GEN-LAST:event_BtnMostrarTodosActionPerformed

    private void BtnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAtrasActionPerformed
        // TODO add your handling code here:
        p1 = new PanelOpcionesConsulta(inicio);
        p1.setSize(1090, 1000);//tamaño del Jpanel
        p1.setLocation(5, 5); // posicion del panel principal
        PanelPrincipal.removeAll();
        PanelPrincipal.add(p1, BorderLayout.CENTER);
        PanelPrincipal.revalidate();
        PanelPrincipal.repaint();
    }//GEN-LAST:event_BtnAtrasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAtras;
    private javax.swing.JButton BtnMostrarTodos;
    private javax.swing.JTable JTableRegistro;
    private javax.swing.JTextField TxtBuscar;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
conectar cc = new conectar();
Connection cn = cc.conexion();
}

