/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import java.awt.BorderLayout;
import static proyecto.InterfazInicio.PanelPrincipal;

/**
 *
 * @author Francisco
 */
public class PanelMonitor extends javax.swing.JPanel {
InterfazInicio inicio;
PanelOpcionesConsulta pl = null;
PanelOpcionesRegistro p2 = null;
PanelAjustesEstudiante a1 = null;
PanelReporte pr = null;
    /**
     * Creates new form PanelMonitor
     * @param n
     */

    public PanelMonitor(InterfazInicio n) {
        initComponents();
        inicio = n;

//        
    }
        public PanelMonitor() {
        initComponents();
       
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JlReporte = new javax.swing.JLabel();
        JlRegistrar1 = new javax.swing.JLabel();
        JlConsultar = new javax.swing.JLabel();
        JlAjustes = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        JlCerrarSesion = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        Eliminar = new javax.swing.JLabel();
        CerrarSesion = new javax.swing.JLabel();
        Registrar = new javax.swing.JLabel();
        Consultar = new javax.swing.JLabel();
        Ajustes = new javax.swing.JLabel();
        JlIniciarSesion = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        Iniciar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1090, 1000));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JlReporte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JlReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Reportes.png"))); // NOI18N
        JlReporte.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                JlReporteMouseMoved(evt);
            }
        });
        JlReporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JlReporteMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JlReporteMouseExited(evt);
            }
        });
        add(JlReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 90, 90));

        JlRegistrar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JlRegistrar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-editar-archivo-96.png"))); // NOI18N
        JlRegistrar1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                JlRegistrar1MouseMoved(evt);
            }
        });
        JlRegistrar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JlRegistrar1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JlRegistrar1MouseExited(evt);
            }
        });
        add(JlRegistrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 100, 90));

        JlConsultar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JlConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-consulta-96.png"))); // NOI18N
        JlConsultar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                JlConsultarMouseMoved(evt);
            }
        });
        JlConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JlConsultarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JlConsultarMouseExited(evt);
            }
        });
        add(JlConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 220, 90, 100));

        JlAjustes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JlAjustes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-ajustes-96.png"))); // NOI18N
        JlAjustes.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                JlAjustesMouseMoved(evt);
            }
        });
        JlAjustes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JlAjustesMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JlAjustesMouseExited(evt);
            }
        });
        add(JlAjustes, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, 90, 100));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Reportes");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Registrar ");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Consultar ");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 320, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Ajustes");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 460, -1, -1));

        JlCerrarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JlCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-salida-96.png"))); // NOI18N
        JlCerrarSesion.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                JlCerrarSesionMouseMoved(evt);
            }
        });
        JlCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JlCerrarSesionMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JlCerrarSesionMouseExited(evt);
            }
        });
        add(JlCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 360, 90, 100));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setText("Cerrar Sesion");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 460, -1, -1));
        add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 180, 130));
        add(CerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 360, 180, 130));
        add(Registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 180, 130));
        add(Consultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 220, 180, 130));
        add(Ajustes, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 180, 130));

        JlIniciarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JlIniciarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/internetmonitor_102153.png"))); // NOI18N
        JlIniciarSesion.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                JlIniciarSesionMouseMoved(evt);
            }
        });
        JlIniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JlIniciarSesionMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JlIniciarSesionMouseExited(evt);
            }
        });
        add(JlIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 100, 100));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setText("Iniciar Sesion");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, -1, -1));
        add(Iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 180, 130));
    }// </editor-fold>//GEN-END:initComponents

    private void JlRegistrar1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlRegistrar1MouseMoved
        // TODO add your handling code here:
        Registrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_JlRegistrar1MouseMoved

    private void JlRegistrar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlRegistrar1MouseExited
        // TODO add your handling code here:
        Registrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_JlRegistrar1MouseExited

    private void JlReporteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlReporteMouseExited
        // TODO add your handling code here:
        Eliminar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_JlReporteMouseExited

    private void JlReporteMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlReporteMouseMoved
        // TODO add your handling code here:
         Eliminar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_JlReporteMouseMoved

    private void JlConsultarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlConsultarMouseExited
        // TODO add your handling code here:
        Consultar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_JlConsultarMouseExited

    private void JlConsultarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlConsultarMouseMoved
        // TODO add your handling code here:
        Consultar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_JlConsultarMouseMoved

    private void JlAjustesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlAjustesMouseExited
        // TODO add your handling code here:
        Ajustes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_JlAjustesMouseExited

    private void JlAjustesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlAjustesMouseMoved
        // TODO add your handling code here:
        Ajustes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_JlAjustesMouseMoved

    private void JlRegistrar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlRegistrar1MouseClicked
        // TODO add your handling code here:
                    p2 = new PanelOpcionesRegistro(inicio);
                    p2.setSize(1090, 1000);//tamaño del Jpanel
                    p2.setLocation(5, 5); // posicion del panel principal
                    PanelPrincipal.removeAll();
                    PanelPrincipal.add(p2, BorderLayout.CENTER);
                    PanelPrincipal.revalidate();
                    PanelPrincipal.repaint();
    }//GEN-LAST:event_JlRegistrar1MouseClicked

    private void JlConsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlConsultarMouseClicked
        // TODO add your handling code here:
                    pl = new PanelOpcionesConsulta(inicio);
                    pl.setSize(1090, 1000);//tamaño del Jpanel
                    pl.setLocation(5, 5); // posicion del panel principal
                    PanelPrincipal.removeAll();
                    PanelPrincipal.add(pl, BorderLayout.CENTER);
                    PanelPrincipal.revalidate();
                    PanelPrincipal.repaint();
    }//GEN-LAST:event_JlConsultarMouseClicked

    private void JlIniciarSesionMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlIniciarSesionMouseMoved
        // TODO add your handling code here:
        Iniciar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_JlIniciarSesionMouseMoved

    private void JlIniciarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlIniciarSesionMouseClicked
        // TODO add your handling code here:

        InterfazSesion interfazsesion = new InterfazSesion(inicio);
        interfazsesion.setVisible(true);
        inicio.setVisible(false);

    }//GEN-LAST:event_JlIniciarSesionMouseClicked

    private void JlIniciarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlIniciarSesionMouseExited
        // TODO add your handling code here:
        Iniciar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_JlIniciarSesionMouseExited

    private void JlAjustesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlAjustesMouseClicked
        // TODO add your handling code here:
                    a1 = inicio.getConfiguracion();
                    a1.setSize(1090, 1000);//tamaño del Jpanel
                    a1.setLocation(5, 5); // posicion del panel principal
                    PanelPrincipal.removeAll();
                    PanelPrincipal.add(a1, BorderLayout.CENTER);
                    PanelPrincipal.revalidate();
                    PanelPrincipal.repaint();
    }//GEN-LAST:event_JlAjustesMouseClicked

    private void JlCerrarSesionMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlCerrarSesionMouseMoved
        // TODO add your handling code here:
          CerrarSesion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_JlCerrarSesionMouseMoved

    private void JlCerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlCerrarSesionMouseExited
        // TODO add your handling code here:
         CerrarSesion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_JlCerrarSesionMouseExited

    private void JlCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlCerrarSesionMouseClicked
        // TODO add your handling code here:

          //vuelve el panel principal
        PanelPrincipal.removeAll();
        PanelPrincipal.revalidate();
        PanelPrincipal.repaint();
//        limpia la caja de texto
        inicio.Limpiar();
        //desbloquea la caja de texto
        inicio.Desbloquear();
        //el jLabel de cerrar sesion se oculta y foto por defecto
        inicio.CerrarSesionFoto();
        //botones
        inicio.BotonDesbloquear();
        //desbloquear
        inicio.desocultar();
        
        
       
    }//GEN-LAST:event_JlCerrarSesionMouseClicked

    private void JlReporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlReporteMouseClicked
        // TODO add your handling code here:
                    pr = new PanelReporte(inicio);
                    pr.setSize(1090, 1000);//tamaño del Jpanel
                    pr.setLocation(5, 5); // posicion del panel principal
                    PanelPrincipal.removeAll();
                    PanelPrincipal.add(pr, BorderLayout.CENTER);
                    PanelPrincipal.revalidate();
                    PanelPrincipal.repaint();
    }//GEN-LAST:event_JlReporteMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ajustes;
    private javax.swing.JLabel CerrarSesion;
    private javax.swing.JLabel Consultar;
    private javax.swing.JLabel Eliminar;
    private javax.swing.JLabel Iniciar;
    private javax.swing.JLabel JlAjustes;
    private javax.swing.JLabel JlCerrarSesion;
    private javax.swing.JLabel JlConsultar;
    private javax.swing.JLabel JlIniciarSesion;
    private javax.swing.JLabel JlRegistrar1;
    private javax.swing.JLabel JlReporte;
    private javax.swing.JLabel Registrar;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    // End of variables declaration//GEN-END:variables

  

    
}
