/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import java.awt.BorderLayout;
import static proyecto.InterfazInicio.PanelPrincipal;

/**
 *
 * @author Francisco
 */
public class PanelOpcionesRegistro extends javax.swing.JPanel {
InterfazInicio inicio;
PanelRegistrarDocente p1 = null;
PanelMonitor p2 = null;
PanelRegistrarEstudiante p3 = null;

    /**
     * Creates new form PanelMonitor
     * @param n
     */
public PanelOpcionesRegistro(InterfazInicio n) {
        initComponents();
        inicio = n;
        
    }

   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JlRegistrarDocente = new javax.swing.JLabel();
        JlAtras = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        RegistrarDocente = new javax.swing.JLabel();
        Atras = new javax.swing.JLabel();
        JlRegistrarEstudiante = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        RegistrarEstudiante = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1090, 1000));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JlRegistrarDocente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JlRegistrarDocente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/RegistrarProfesor.png"))); // NOI18N
        JlRegistrarDocente.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                JlRegistrarDocenteMouseMoved(evt);
            }
        });
        JlRegistrarDocente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JlRegistrarDocenteMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JlRegistrarDocenteMouseExited(evt);
            }
        });
        add(JlRegistrarDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 100, 100));

        JlAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-salida-96.png"))); // NOI18N
        JlAtras.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                JlAtrasMouseMoved(evt);
            }
        });
        JlAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JlAtrasMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JlAtrasMouseExited(evt);
            }
        });
        add(JlAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 220, 90, 100));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Registrar Docente ");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Atras");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 320, -1, -1));
        add(RegistrarDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 180, 130));
        add(Atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 220, 180, 130));

        JlRegistrarEstudiante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JlRegistrarEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/RegistrarEstudiante.png"))); // NOI18N
        JlRegistrarEstudiante.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                JlRegistrarEstudianteMouseMoved(evt);
            }
        });
        JlRegistrarEstudiante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JlRegistrarEstudianteMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JlRegistrarEstudianteMouseExited(evt);
            }
        });
        add(JlRegistrarEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 100, 100));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setText("Registrar Estudiante");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, -1, -1));
        add(RegistrarEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 180, 130));
    }// </editor-fold>//GEN-END:initComponents

    private void JlRegistrarDocenteMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlRegistrarDocenteMouseMoved
        // TODO add your handling code here:
        RegistrarDocente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_JlRegistrarDocenteMouseMoved

    private void JlRegistrarDocenteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlRegistrarDocenteMouseExited
        // TODO add your handling code here:
        RegistrarDocente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_JlRegistrarDocenteMouseExited

    private void JlAtrasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlAtrasMouseExited
        // TODO add your handling code here:
        Atras.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_JlAtrasMouseExited

    private void JlAtrasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlAtrasMouseMoved
        // TODO add your handling code here:
        Atras.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_JlAtrasMouseMoved

    private void JlRegistrarDocenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlRegistrarDocenteMouseClicked
        // TODO add your handling code here:
                    p1 = new PanelRegistrarDocente(inicio);
                    p1.setSize(1090, 1000);//tamaño del Jpanel
                    p1.setLocation(5, 5); // posicion del panel principal
                    PanelPrincipal.removeAll();
                    PanelPrincipal.add(p1, BorderLayout.CENTER);
                    PanelPrincipal.revalidate();
                    PanelPrincipal.repaint();
    }//GEN-LAST:event_JlRegistrarDocenteMouseClicked

    private void JlAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlAtrasMouseClicked
        // TODO add your handling code here:
                    p2 = new PanelMonitor(inicio);
                    p2.setSize(1090, 1000);//tamaño del Jpanel
                    p2.setLocation(5, 5); // posicion del panel principal
                    PanelPrincipal.removeAll();
                    PanelPrincipal.add(p2, BorderLayout.CENTER);
                    PanelPrincipal.revalidate();
                    PanelPrincipal.repaint();
                    
                    
                 
    }//GEN-LAST:event_JlAtrasMouseClicked

    private void JlRegistrarEstudianteMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlRegistrarEstudianteMouseMoved
        // TODO add your handling code here:
        RegistrarEstudiante.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_JlRegistrarEstudianteMouseMoved

    private void JlRegistrarEstudianteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlRegistrarEstudianteMouseClicked
        // TODO add your handling code here:
                    p3 = new PanelRegistrarEstudiante(inicio);
                    p3.setSize(1090, 1000);//tamaño del Jpanel
                    p3.setLocation(5, 5); // posicion del panel principal
                    PanelPrincipal.removeAll();
                    PanelPrincipal.add(p3, BorderLayout.CENTER);
                    PanelPrincipal.revalidate();
                    PanelPrincipal.repaint();

    }//GEN-LAST:event_JlRegistrarEstudianteMouseClicked

    private void JlRegistrarEstudianteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlRegistrarEstudianteMouseExited
        // TODO add your handling code here:
        RegistrarEstudiante.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_JlRegistrarEstudianteMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Atras;
    private javax.swing.JLabel JlAtras;
    private javax.swing.JLabel JlRegistrarDocente;
    private javax.swing.JLabel JlRegistrarEstudiante;
    private javax.swing.JLabel RegistrarDocente;
    private javax.swing.JLabel RegistrarEstudiante;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel20;
    // End of variables declaration//GEN-END:variables

  

    
}
