/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import java.awt.BorderLayout;
import static proyecto.InterfazInicio.PanelPrincipal;

/**
 *
 * @author Francisco
 */
public class PanelOpcionesConsulta extends javax.swing.JPanel {
    InterfazInicio inicio;
    PanelConsultarDocente p1 = null;
    PanelConsultarEstudiante p2 = null;
    PanelMonitor p3 = null;

    /**
     * Creates new form PanelMonitor
     */
        public PanelOpcionesConsulta(InterfazInicio n) {
        initComponents();
        inicio = n;
       
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JlConsultarDocente = new javax.swing.JLabel();
        JlAtras = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        ConsultarDocente = new javax.swing.JLabel();
        Atras = new javax.swing.JLabel();
        JlConsultarEstudiante = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        ConsultarEstudiante = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1090, 1000));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JlConsultarDocente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Consulta_Docente.png"))); // NOI18N
        JlConsultarDocente.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                JlConsultarDocenteMouseMoved(evt);
            }
        });
        JlConsultarDocente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JlConsultarDocenteMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JlConsultarDocenteMouseExited(evt);
            }
        });
        add(JlConsultarDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 100, 100));

        JlAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-salida-96.png"))); // NOI18N
        JlAtras.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                JlAtrasMouseMoved(evt);
            }
        });
        JlAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JlAtrasMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JlAtrasMouseExited(evt);
            }
        });
        add(JlAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 220, 90, 100));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Consultar Docente ");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Atras");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 320, -1, -1));
        add(ConsultarDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 180, 130));
        add(Atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 220, 180, 130));

        JlConsultarEstudiante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Consulta_Estudiante.png"))); // NOI18N
        JlConsultarEstudiante.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                JlConsultarEstudianteMouseMoved(evt);
            }
        });
        JlConsultarEstudiante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JlConsultarEstudianteMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JlConsultarEstudianteMouseExited(evt);
            }
        });
        add(JlConsultarEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 100, 100));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setText("Consultar Estudiante");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, -1, -1));
        add(ConsultarEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 180, 130));
    }// </editor-fold>//GEN-END:initComponents

    private void JlConsultarDocenteMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlConsultarDocenteMouseMoved
        // TODO add your handling code here:
        ConsultarDocente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_JlConsultarDocenteMouseMoved

    private void JlConsultarDocenteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlConsultarDocenteMouseExited
        // TODO add your handling code here:
        ConsultarDocente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_JlConsultarDocenteMouseExited

    private void JlAtrasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlAtrasMouseExited
        // TODO add your handling code here:
        Atras.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_JlAtrasMouseExited

    private void JlAtrasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlAtrasMouseMoved
        // TODO add your handling code here:
        Atras.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_JlAtrasMouseMoved

    private void JlConsultarDocenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlConsultarDocenteMouseClicked
        // TODO add your handling code here:
                    p1 = new PanelConsultarDocente(inicio);
                    p1.setSize(1090, 1000);//tamaño del Jpanel
                    p1.setLocation(5, 5); // posicion del panel principal
                    PanelPrincipal.removeAll();
                    PanelPrincipal.add(p1, BorderLayout.CENTER);
                    PanelPrincipal.revalidate();
                    PanelPrincipal.repaint();
    }//GEN-LAST:event_JlConsultarDocenteMouseClicked

    private void JlAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlAtrasMouseClicked
        // TODO add your handling code here:
                    p3 = new PanelMonitor(inicio);
                    p3.setSize(1090, 1000);//tamaño del Jpanel
                    p3.setLocation(5, 5); // posicion del panel principal
                    PanelPrincipal.removeAll();
                    PanelPrincipal.add(p3, BorderLayout.CENTER);
                    PanelPrincipal.revalidate();
                    PanelPrincipal.repaint();
    }//GEN-LAST:event_JlAtrasMouseClicked

    private void JlConsultarEstudianteMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlConsultarEstudianteMouseMoved
        // TODO add your handling code here:
        ConsultarEstudiante.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_JlConsultarEstudianteMouseMoved

    private void JlConsultarEstudianteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlConsultarEstudianteMouseClicked
        // TODO add your handling code here:
                    p2 = new PanelConsultarEstudiante(inicio);
                    p2.setSize(1090, 1000);//tamaño del Jpanel
                    p2.setLocation(5, 5); // posicion del panel principal
                    PanelPrincipal.removeAll();
                    PanelPrincipal.add(p2, BorderLayout.CENTER);
                    PanelPrincipal.revalidate();
                    PanelPrincipal.repaint();

    }//GEN-LAST:event_JlConsultarEstudianteMouseClicked

    private void JlConsultarEstudianteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlConsultarEstudianteMouseExited
        // TODO add your handling code here:
        ConsultarEstudiante.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_JlConsultarEstudianteMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Atras;
    private javax.swing.JLabel ConsultarDocente;
    private javax.swing.JLabel ConsultarEstudiante;
    private javax.swing.JLabel JlAtras;
    private javax.swing.JLabel JlConsultarDocente;
    private javax.swing.JLabel JlConsultarEstudiante;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel20;
    // End of variables declaration//GEN-END:variables

  

    
}
