/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import Conectar.conectar;
import java.sql.*;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import static proyecto.InterfazInicio.PanelPrincipal;

/**
 *
 * @author Francisco
 */
public class PanelConsultarDocente extends javax.swing.JPanel {
    DefaultTableModel modelo;
    InterfazInicio inicio;
    PanelOpcionesConsulta p1 = null;

    /**
     * Creates new form PanelConsultar
     * @param n
     */
    @SuppressWarnings("unchecked")
    public PanelConsultarDocente(InterfazInicio n) {
        
        initComponents();
        mostrarusuarios("");
        inicio = n;
        
        JTableDocente.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
        JTableDocente.getTableHeader().setOpaque(false);
        JTableDocente.getTableHeader().setBackground(new Color(32, 136, 203));
        JTableDocente.getTableHeader().setForeground(new Color(255,255,255));
        JTableDocente.setRowHeight(25);
        
    }
    @SuppressWarnings("unchecked")
     void mostrarusuarios(String valor){
   String mostrar="SELECT * FROM docente WHERE CONCAT(IdDocente,DocumentoIdentidad,Nombres,Apellidos,Email,Genero,TipoUsuario,Password,Foto) LIKE '%"+valor+"%'";    
   String [] titulos= {"Documento Identidad","Nombres","Apellidos","Email","Genero","Tipo Usuario"};
   modelo=new  DefaultTableModel(null,titulos);   
   String datos []= new String[8];
   String sql="SELECT * FROM  docente"; 
        try {
            Statement st = (Statement) cn.createStatement();
            ResultSet rs = st.executeQuery(mostrar);
            while(rs.next())
            {
                
                datos[0] = rs.getString("DocumentoIdentidad");
                datos[1] = rs.getString("Nombres");
                datos[2] = rs.getString("Apellidos");
                datos[3] = rs.getString("Email");
                datos[4] = rs.getString("Genero");
                datos[5] = rs.getString("TipoUsuario");
                datos[6] = rs.getString("Password");
//                datos[7] = rs.getBlob("Foto").toString();
               
                        
                modelo.addRow(datos);
            }
            JTableDocente.setModel(modelo);
       } catch (SQLException e) {
             JOptionPane.showMessageDialog(this,e);

        }
  
  
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        BtnMostrarTodos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableDocente = new javax.swing.JTable();
        TxtBuscar = new rscomponentshade.RSTextFieldShade();
        BtnAtras = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Base de Datos Docente"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Busqueda: ");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 27, -1, -1));

        BtnMostrarTodos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/button_mostrar-todo.png"))); // NOI18N
        BtnMostrarTodos.setBorderPainted(false);
        BtnMostrarTodos.setContentAreaFilled(false);
        BtnMostrarTodos.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/button_mostrar-todo_on.png"))); // NOI18N
        BtnMostrarTodos.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Botones/button_mostrar-todo_on.png"))); // NOI18N
        BtnMostrarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMostrarTodosActionPerformed(evt);
            }
        });
        jPanel2.add(BtnMostrarTodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 15, 156, -1));

        JTableDocente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        JTableDocente.setRowHeight(25);
        JTableDocente.setSelectionBackground(new java.awt.Color(232, 57, 95));
        JTableDocente.setShowVerticalLines(false);
        jScrollPane1.setViewportView(JTableDocente);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 117, 970, 486));

        TxtBuscar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TxtBuscar.setPlaceholder("");
        TxtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtBuscarKeyReleased(evt);
            }
        });
        jPanel2.add(TxtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 25, 160, 30));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 620));

        BtnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/button_atras.png"))); // NOI18N
        BtnAtras.setBorderPainted(false);
        BtnAtras.setContentAreaFilled(false);
        BtnAtras.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/button_atras_on.png"))); // NOI18N
        BtnAtras.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/button_atras_on.png"))); // NOI18N
        BtnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAtrasActionPerformed(evt);
            }
        });
        add(BtnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(838, 683, 160, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void BtnMostrarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMostrarTodosActionPerformed
        // TODO add your handling code here:
        mostrarusuarios("");
        TxtBuscar.setText("");
    }//GEN-LAST:event_BtnMostrarTodosActionPerformed

    private void BtnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAtrasActionPerformed
        // TODO add your handling code here:
        p1 = new PanelOpcionesConsulta(inicio);
        p1.setSize(1090, 1000);//tamaño del Jpanel
        p1.setLocation(5, 5); // posicion del panel principal
        PanelPrincipal.removeAll();
        PanelPrincipal.add(p1, BorderLayout.CENTER);
        PanelPrincipal.revalidate();
        PanelPrincipal.repaint();
    }//GEN-LAST:event_BtnAtrasActionPerformed

    private void TxtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtBuscarKeyReleased
        // TODO add your handling code here:
        mostrarusuarios(TxtBuscar.getText());
    }//GEN-LAST:event_TxtBuscarKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAtras;
    private javax.swing.JButton BtnMostrarTodos;
    private javax.swing.JTable JTableDocente;
    private rscomponentshade.RSTextFieldShade TxtBuscar;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
conectar cc = new conectar();
Connection cn = cc.conexion();
}

